{% set name = "svglib" %}
{% set version = "1.3.0" %}
{% set hash = "a38998b95d1bb99564dc9dffaf15e4e9453761f2790d2dd4147a4ad5fbac1078" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - python >=3.7
    - reportlab
    - lxml
    - tinycss2 >=0.6.0
    - cssselect2 >=0.2.0

test:
  requires:
    - pytest-runner
  imports:
    - svglib
  source_files:
    - tests
  commands:
    # Skipping tests/test_samples.py because it is too slow.
    - pytest tests -k "not test_samples"

about:
  home: https://github.com/deeplook/svglib
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: A pure-Python library for reading and converting SVG
  license_family: LGPL

extra:
  recipe-maintainers:
    - nicoddemus
