{% set name = "svglib" %}
{% set version = "0.9.3" %}
{% set hash_type = "sha256" %}
{% set hash = "91e6becb5698c4328584ce86642d9024be1db043741b0af5518d4420bd3e5d5e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - pip
    - python

  run:
    - python
    - reportlab
    - lxml
    - tinycss2 >=0.6.0
    - cssselect2 >=0.2.0

test:
  requires:
    - pytest-runner
  imports:
    - svglib
  source_files:
    - tests
  commands:
    # skipping tests/test_samples.py because it is too slow
    - pytest tests -k "not test_samples"

about:
  home: https://github.com/deeplook/svglib
  license: LGPL 3
  license_file: LICENSE.txt
  summary: 'A pure-Python library for reading and converting SVG'
  license_family: LGPL

extra:
  recipe-maintainers:
    - nicoddemus
