{% set name = "svglib" %}
{% set version = "1.5.0" %}
{% set hash = "bd76385a8ebad5ccc406e0e110d9db6ca256e84dba08c4169ca72d4a2df27d78" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - python >=3.7
    - reportlab
    - lxml
    - tinycss2 >=0.6.0
    - cssselect2 >=0.2.0

test:
  requires:
    - pytest-runner
  imports:
    - svglib
  source_files:
    - tests

about:
  home: https://github.com/deeplook/svglib
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: A pure-Python library for reading and converting SVG
  license_family: LGPL

extra:
  recipe-maintainers:
    - nicoddemus
