appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: jLChJktnnbEAfQvRfn93xVDDPQR5eMf8cfwLPwoS103bl3i+X1cTqVmx9oS3ORMRAT50JGveifDGHR9Zktl9IxQIQkSWF181XRrUws4PX4k8a2j42cjtQri+FFCA9S0quqEZy8CEBUPHPytU6mTsL9GneEHz0Y2yxMWdlKI4201xt5sq4yCY5vpyeZIH82PKLqSZzUeb8ztyO2B+3sl6Hf/FQn1Wtjy6NX/hPrWSjLECdMLcpl0EQLfU1ZCyEInu9YhkNvtgF4imDGrlnQAU6WCu+q0TMdaHknVefU6MFYWFohuMO9cBLUH7YzlXI5KULWgSMzH6YHO02takCfhBs2XRD0cQjAAR06F/xt/roQeaB+sqo9bNwH2OdA+NkGEYRMcbCrg7EoMjCSck+ZQFfZQw24bfF5XS9HSENS/P2hoNkrXcKp0r2zGoUkCzhOGTqKWBuaRvREbTr+ysvogmKqo+qwkasRKsAU7uo8FG4xwW7/kSnxBP2Z8TlVa3uBI1gxCu04eWoQ4Ujw63wRixxfr3aXvPRW67DDSYWaMu0SabrLwgZt0UxT33Pn+Jb/YG2wKW3vl7Sj3N+M03pbOe6QBvPxRKAG0/Qo69J0YYJJlKB45/y2Frks0ZKB9CCXZONySnElDHXhLSrYPIcwuyFtMU9bDPIsXzQZ3hmVQICpk=}
provider:
  win: azure
conda_forge_output_validation: false
