travis:
  secure:
    BINSTAR_TOKEN: m8i6eKc0oEwLJ4vBJ2OIRegnUSIV+NXK2dOfwrOqI3gm2wDpivDE6igMp935D/52qpUE0UkRov9/8s/X9zZAN2ta4iIEs9AK1c+x6MukPoVEc4KgCnnzz0XC0PY5rpLkX/ZVFfI5v12GXrC1S96sWGtFDAtBVuo9mPzilhCvgkYAK1KNPMvjTZeta/KDe4L6QnnIU7n0HgQs1U0VRv/5zTSbtvxkTrS3Mk3TFGpuIqNJn4qk/J3hSv/8/j5Ueg8wnzOtOSoa5x7CZQiLF7XDgQMl9br1n3xyF3VBskfB9h4jsShfBFGcCdlbCUmWS8ABxaCMWe9Ukk0tFknfp/pPQsNRZcE5rc23WdmKbzfAb7lT/Nqd0zAHEjWjr7nPbt6x17kheh+LZ6RiMqqkd3MdwbztKUSTB+o6w1yf/88syuCqz/5w4+DC+hxtH2GVgFHXMxP4PLMX9nv7A5Zn/chNe959IBYA6WqOb69Uq1eXxFkKu61PurxABwRg8yhYPi8fBmmr37ZjjLFYCS6lbPp24yjlhc2Tm9jn/sKzCfeS9GjWcPKjkPlJxHYFROQ8Gfu2xdsiA63Sxy5eavr1zvtxUE8+1dRcPMhENPVTgTcwpiFELiVtEK32near80TRZFFrQ3vUj6qXKvmkCiguGgvMa3ixIdDiYnZRTitBkG9sKyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
